# TCL File Generated by Component Editor 9.1sp2
# Sun Jun 20 09:50:55 JST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | AvalonIF_Mmc "AvalonIF_Mmc" v1.0
# | null 2010.06.20.09:50:55
# | 
# | 
# | ../mmc_spi/AvalonIF_Mmc.vhd
# | 
# |    ./avalonif_mmc.vhd syn
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module AvalonIF_Mmc
# | 
set_module_property DESCRIPTION ""
set_module_property NAME AvalonIF_Mmc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Unknown Group"
set_module_property DISPLAY_NAME AvalonIF_Mmc
set_module_property TOP_LEVEL_HDL_FILE AvalonIF_Mmc.vhd
set_module_property TOP_LEVEL_HDL_MODULE AvalonIF_Mmc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file AvalonIF_Mmc.vhd SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
add_interface_port clock reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ext
# | 
add_interface ext conduit end

set_interface_property ext ENABLED true

add_interface_port ext MMC_nCS export Output 1
add_interface_port ext MMC_SCK export Output 1
add_interface_port ext MMC_SDO export Output 1
add_interface_port ext MMC_SDI export Input 1
add_interface_port ext MMC_CD export Input 1
add_interface_port ext MMC_WP export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment NATIVE
set_interface_property s1 associatedClock clock
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK clock
set_interface_property s1 ENABLED true

add_interface_port s1 chipselect chipselect Input 1
add_interface_port s1 address address Input 2
add_interface_port s1 read read Input 1
add_interface_port s1 readdata readdata Output 32
add_interface_port s1 write write Input 1
add_interface_port s1 writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_irq
# | 
add_interface s1_irq interrupt end
set_interface_property s1_irq associatedAddressablePoint s1

set_interface_property s1_irq ASSOCIATED_CLOCK clock
set_interface_property s1_irq ENABLED true

add_interface_port s1_irq irq irq Output 1
# | 
# +-----------------------------------
